plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'config/environments/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/StringHashKeys:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
