AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'config/environments/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/migrate/*'
  NewCops: enable
  TargetRubyVersion: 3.4
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
plugins:
  - rubocop-rails
  - rubocop-performance
